/**
 * Short labels that live in components rather than in the page content (defaults.ts): menu
 * items, button text, form labels, screen-reader names. One entry per label, in both languages.
 * Server components read them with tr(locale, key); client components with useT().
 */
import type { Locale } from '../locale';

const en = {
  // Menu and footer
  'nav.home': 'Home',
  'nav.about': 'About',
  'nav.projects': 'Projects',
  'nav.services': 'Services',
  'nav.contact': 'Contact',
  'nav.main': 'Main',
  'nav.menu': 'Menu',
  'nav.openMenu': 'Open menu',
  'nav.closeMenu': 'Close menu',
  'nav.footer': 'Footer',
  'nav.homeLink': 'Shah Noori home',
  'nav.switchLanguage': 'العربية',
  'nav.switchLanguageLabel': 'عرض الموقع بالعربية',
  'footer.rights': 'All rights reserved.',
  'footer.designedBy': 'Designed by',
  'footer.developedBy': 'Developed by',
  'footer.poweredBy': 'Powered by',
  'footer.address': 'Doha, Qatar',

  // Section labels
  'label.about': 'About Us',
  'label.process': 'Process',
  'label.projects': 'Projects',
  'label.services': 'Services',
  'label.ourServices': 'Our Services',
  'label.ourStory': 'Our Story',
  'label.ourClients': 'Our Clients',
  'label.faq': 'FAQ',
  'label.contact': 'Contact Us',
  'label.testimonials': 'Client testimonials',

  // Buttons and small actions
  'action.whatsapp': 'Enquire on WhatsApp',
  'action.whatsappChat': 'Chat on WhatsApp',
  'action.backToTop': 'Back to top',
  'action.top': 'Top',
  'action.show': 'Show',
  'action.viewProject': 'View project',
  'action.previousProject': 'Previous project',
  'action.nextProject': 'Next project',
  'whatsapp.default': 'Hello Shah Noori, I would like to make an enquiry.',
  'whatsapp.discuss': 'Hello Shah Noori, I would like to discuss a project.',

  // Loading screen and page change
  'preloader.label': 'Loading Shah Noori',
  'preloader.note1': 'Planning the space…',
  'preloader.note2': 'Drafting the design…',
  'preloader.note3': 'Building with care…',
  'preloader.note4': 'Fitting out the interiors…',
  'preloader.final': 'Welcome to Shah Noori.',
  'preloader.tagline': '· Interior & Fit-out · Doha',
  'page.project': 'Project',

  // Projects list and cards
  'projects.featured': 'Featured Project',
  'projects.statShown': 'Projects showcased',
  'projects.statTypes': 'Types of space',
  'projects.statSince': 'Portfolio since',
  'projects.space': 'Space',
  'projects.service': 'Service',
  'projects.all': 'All',
  'projects.filterSpace': 'Filter projects by type of space',
  'projects.filterService': 'Filter projects by service',
  'projects.showing': 'Showing',
  'projects.one': 'project',
  'projects.many': 'projects',
  'projects.none': 'No projects match these filters yet',
  'projects.viewAll': 'View all projects',
  'projects.loading': 'Loading projects…',
  'projects.noFeatured': 'Featured projects will appear here once they are marked as featured in the Studio.',
  'fact.category': 'Category',
  'fact.client': 'Client',
  'fact.location': 'Location',
  'fact.year': 'Year',

  // Kinds of place and services (filters, cards)
  'space.retail': 'Retail',
  'space.office': 'Office',
  'space.exhibition': 'Exhibition',
  'space.cafe': 'Café & Restaurant',
  'space.hospitality': 'Hospitality',
  'space.healthcare': 'Healthcare',
  'space.residential': 'Residential',
  'service.interior': 'Interior & Fit-out',
  'service.mep': 'MEP',
  'service.civil': 'Civil',
  'category.interior': 'Interior',
  'category.mechanical': 'Mechanical',
  'category.electrical': 'Electrical',
  'category.plumbing': 'Plumbing',
  'category.civil': 'Civil',

  // One project's page
  'project.breadcrumb': 'Breadcrumb',
  'project.overview': 'Project Overview',
  'project.comingSoon': 'Full project details are coming soon.',
  'project.similar': 'Planning something similar?',
  'project.talk': 'Talk to our team about your project.',
  'project.consultation': 'Request a consultation',
  'project.featuredPhoto': 'Featured photo',
  'project.fromClient': 'From the client',
  'project.gallery': 'Gallery',
  'project.photo': 'photo',
  'project.photos': 'photos',
  'project.enlarge': 'click to enlarge',
  'project.like': 'Like what you see?',
  'project.askBefore': 'Ask us about',
  'project.askAfter': 'on WhatsApp. We usually reply the same day.',
  'project.more': 'More projects',
  'project.previous': 'Previous project',
  'project.next': 'Next project',
  'project.moreWork': 'More Work',
  'project.related': 'Related Projects',
  'project.viewAllKind': 'View all projects',
  'project.metaKind': 'Project in',
  'project.qatar': 'Qatar',
  'project.waSimilarBefore': 'Hello Shah Noori, I saw your project',
  'project.waSimilarAfter': 'and would like to discuss something similar.',
  'project.waLookedBefore': 'Hello Shah Noori, I just looked at your project',
  'project.waLookedAfter': 'on your website and would like to know more.',

  // Photo viewer
  'gallery.open': 'Open photo',
  'gallery.of': 'of',
  'gallery.viewer': 'photo viewer',
  'gallery.close': 'Close photo viewer',
  'gallery.previous': 'Previous photo',
  'gallery.next': 'Next photo',
  'gallery.show': 'Show photo',
  'stars.outOf': 'out of 5 stars',

  // Contact page and form
  'contact.mapTitle': 'Shah Noori location map',
  'contact.mapLink': 'Map: Find Our Location',
  'form.thanks': 'Thank you — your enquiry is in.',
  'form.thanksText': 'Our team will get back to you shortly. A confirmation has been sent to',
  'form.another': 'Send another enquiry',
  'form.trap': 'Leave this field empty',
  'form.name': 'Name',
  'form.namePlaceholder': 'Sheikh Fahad Al-Thani / Eng. Karim',
  'form.phone': 'Phone',
  'form.codeTitle': 'Country code, for example +974',
  'form.codeLabel': 'Country code',
  'form.phoneTitle': 'Phone number, digits only',
  'form.email': 'Email',
  'form.projectType': 'Project Type',
  'form.details': 'Project details',
  'form.optional': '(optional)',
  'form.detailsPlaceholder': 'Location, size, timeline…',
  'form.nda': 'All drawings, BoQs, and commercial estimates are bound by strict mutual non-disclosure under Qatari Commercial Law.',
  'form.send': 'Send Enquiry',
  'form.sending': 'Sending…',
  'form.byEmail': 'Request a Project Consultation',
  'form.byWhatsapp': 'Send on WhatsApp instead',
  'form.failed': 'We could not send your enquiry.',
  'form.reply': "We'll reply by email or phone, usually within one working day.",
  'contact.openWhatsapp': '(Open WhatsApp)',
  'form.emailSubject': 'Project consultation request',
  'form.waIntro': 'Hello Shah Noori, I would like to request a project consultation.',
  'form.waName': 'Name',
  'form.waPhone': 'Phone',
  'form.waEmail': 'Email',
  'form.waType': 'Project type',
  'form.waDetails': 'Details',
  'type.civil': 'Civil Construction',
  'type.interior': 'Interior & Fit-Out',
  'type.commercial': 'Commercial Spaces',
  'type.retail': 'Retail Fit-Out',
  'type.hospitality': 'Hospitality Spaces',
  'type.mep': 'MEP Works',
  'type.turnkey': 'Turnkey Contracting',

  // Search and link-preview text
  'meta.home.title': 'Shah Noori | Interior Fit-out & MEP Contractor in Doha',
  'meta.home.description':
    'Shah Noori is an interior fit-out, MEP and civil contracting company in Doha, Qatar. See our completed projects and services, and request a consultation.',
  'meta.about.title': 'About Us | Interior Fit-out Company in Doha',
  'meta.about.description':
    'Shah Noori is an integrated construction and contracting company in Doha, Qatar, with 15+ years of experience in interior fit-out, MEP and civil works.',
  'meta.services.title': 'Interior Fit-out, MEP & Civil Services in Qatar',
  'meta.services.description':
    'Interior fit-out, MEP (mechanical, electrical, plumbing) and civil construction services in Doha, Qatar, delivered end to end by one team.',
  'meta.projects.title': 'Projects | Interior & Fit-out Work in Qatar',
  'meta.projects.description':
    'Interior fit-out, MEP and civil projects completed by Shah Noori across Qatar: offices, shops, cafes, villas and more.',
  'meta.contact.title': 'Contact | Fit-out Contractor in Doha, Qatar',
  'meta.contact.description':
    'Request a project consultation with Shah Noori: interior fit-out, MEP and civil works in Doha, Qatar. Call, WhatsApp or send us a message.',
} as const;

export type UiKey = keyof typeof en;

const ar: Record<UiKey, string> = {
  'nav.home': 'الرئيسية',
  'nav.about': 'من نحن',
  'nav.projects': 'المشاريع',
  'nav.services': 'الخدمات',
  'nav.contact': 'اتصل بنا',
  'nav.main': 'القائمة الرئيسية',
  'nav.menu': 'القائمة',
  'nav.openMenu': 'فتح القائمة',
  'nav.closeMenu': 'إغلاق القائمة',
  'nav.footer': 'روابط التذييل',
  'nav.homeLink': 'الصفحة الرئيسية لـ Shah Noori',
  'nav.switchLanguage': 'English',
  'nav.switchLanguageLabel': 'View the site in English',
  'footer.rights': 'جميع الحقوق محفوظة.',
  'footer.designedBy': 'تصميم',
  'footer.developedBy': 'تطوير',
  'footer.poweredBy': 'برعاية',
  'footer.address': 'الدوحة، قطر',

  'label.about': 'من نحن',
  'label.process': 'منهجيتنا',
  'label.projects': 'المشاريع',
  'label.services': 'الخدمات',
  'label.ourServices': 'خدماتنا',
  'label.ourStory': 'قصتنا',
  'label.ourClients': 'عملاؤنا',
  'label.faq': 'الأسئلة الشائعة',
  'label.contact': 'اتصل بنا',
  'label.testimonials': 'آراء العملاء',

  'action.whatsapp': 'استفسر عبر واتساب',
  'action.whatsappChat': 'تحدّث معنا عبر واتساب',
  'action.backToTop': 'العودة إلى الأعلى',
  'action.top': 'الأعلى',
  'action.show': 'عرض',
  'action.viewProject': 'عرض المشروع',
  'action.previousProject': 'المشروع السابق',
  'action.nextProject': 'المشروع التالي',
  'whatsapp.default': 'مرحبًا Shah Noori، أودّ الاستفسار.',
  'whatsapp.discuss': 'مرحبًا Shah Noori، أودّ مناقشة مشروع.',

  'preloader.label': 'جارٍ تحميل Shah Noori',
  'preloader.note1': 'نخطط المساحة…',
  'preloader.note2': 'نرسم التصميم…',
  'preloader.note3': 'نبني بعناية…',
  'preloader.note4': 'نجهّز المساحات الداخلية…',
  'preloader.final': 'مرحبًا بكم في Shah Noori.',
  'preloader.tagline': '· التشطيبات والتجهيزات الداخلية · الدوحة',
  'page.project': 'المشروع',

  'projects.featured': 'مشروع مميز',
  'projects.statShown': 'المشاريع المعروضة',
  'projects.statTypes': 'أنواع المساحات',
  'projects.statSince': 'أعمالنا منذ',
  'projects.space': 'المساحة',
  'projects.service': 'الخدمة',
  'projects.all': 'الكل',
  'projects.filterSpace': 'تصفية المشاريع حسب نوع المساحة',
  'projects.filterService': 'تصفية المشاريع حسب الخدمة',
  'projects.showing': 'عدد المشاريع المعروضة:',
  'projects.one': '',
  'projects.many': '',
  'projects.none': 'لا توجد مشاريع مطابقة لهذه التصفية حتى الآن',
  'projects.viewAll': 'عرض جميع المشاريع',
  'projects.loading': 'جارٍ تحميل المشاريع…',
  'projects.noFeatured': 'ستظهر المشاريع المميزة هنا بعد تحديدها كمميزة في لوحة التحكم.',
  'fact.category': 'الفئة',
  'fact.client': 'العميل',
  'fact.location': 'الموقع',
  'fact.year': 'السنة',

  'space.retail': 'متاجر التجزئة',
  'space.office': 'المكاتب',
  'space.exhibition': 'المعارض',
  'space.cafe': 'المقاهي والمطاعم',
  'space.hospitality': 'الضيافة',
  'space.healthcare': 'الرعاية الصحية',
  'space.residential': 'السكني',
  'service.interior': 'التشطيبات والتجهيزات الداخلية',
  'service.mep': 'الكهروميكانيكا',
  'service.civil': 'الأعمال المدنية',
  'category.interior': 'الداخلي',
  'category.mechanical': 'الميكانيكا',
  'category.electrical': 'الكهرباء',
  'category.plumbing': 'السباكة',
  'category.civil': 'المدني',

  'project.breadcrumb': 'مسار الصفحة',
  'project.overview': 'نبذة عن المشروع',
  'project.comingSoon': 'ستتوفر تفاصيل المشروع الكاملة قريبًا.',
  'project.similar': 'هل تخطط لمشروع مشابه؟',
  'project.talk': 'تحدّث مع فريقنا عن مشروعك.',
  'project.consultation': 'اطلب استشارة',
  'project.featuredPhoto': 'صورة مميزة',
  'project.fromClient': 'رأي العميل',
  'project.gallery': 'معرض الصور',
  'project.photo': 'صورة',
  'project.photos': 'صور',
  'project.enlarge': 'اضغط للتكبير',
  'project.like': 'هل أعجبك ما رأيت؟',
  'project.askBefore': 'اسألنا عن مشروع',
  'project.askAfter': 'عبر واتساب. نردّ عادةً في اليوم نفسه.',
  'project.more': 'مشاريع أخرى',
  'project.previous': 'المشروع السابق',
  'project.next': 'المشروع التالي',
  'project.moreWork': 'أعمال أخرى',
  'project.related': 'مشاريع ذات صلة',
  'project.viewAllKind': 'عرض جميع المشاريع',
  'project.metaKind': 'مشروع في',
  'project.qatar': 'قطر',
  'project.waSimilarBefore': 'مرحبًا Shah Noori، شاهدت مشروعكم',
  'project.waSimilarAfter': 'وأودّ مناقشة مشروع مشابه.',
  'project.waLookedBefore': 'مرحبًا Shah Noori، اطّلعت للتوّ على مشروعكم',
  'project.waLookedAfter': 'على موقعكم وأودّ معرفة المزيد.',

  'gallery.open': 'فتح الصورة',
  'gallery.of': 'من',
  'gallery.viewer': 'عارض الصور',
  'gallery.close': 'إغلاق عارض الصور',
  'gallery.previous': 'الصورة السابقة',
  'gallery.next': 'الصورة التالية',
  'gallery.show': 'عرض الصورة',
  'stars.outOf': 'من 5 نجوم',

  'contact.mapTitle': 'خريطة موقع Shah Noori',
  'contact.mapLink': 'الخريطة: موقعنا',
  'form.thanks': 'شكرًا لك — تم استلام طلبك.',
  'form.thanksText': 'سيتواصل معك فريقنا قريبًا. تم إرسال رسالة تأكيد إلى',
  'form.another': 'إرسال طلب آخر',
  'form.trap': 'اترك هذا الحقل فارغًا',
  'form.name': 'الاسم',
  'form.namePlaceholder': 'الشيخ فهد آل ثاني / م. كريم',
  'form.phone': 'الهاتف',
  'form.codeTitle': 'رمز الدولة، مثال: ‎+974',
  'form.codeLabel': 'رمز الدولة',
  'form.phoneTitle': 'رقم الهاتف، أرقام فقط',
  'form.email': 'البريد الإلكتروني',
  'form.projectType': 'نوع المشروع',
  'form.details': 'تفاصيل المشروع',
  'form.optional': '(اختياري)',
  'form.detailsPlaceholder': 'الموقع، المساحة، الجدول الزمني…',
  'form.nda': 'جميع المخططات وجداول الكميات والتقديرات التجارية تخضع لالتزام متبادل صارم بعدم الإفصاح وفق القانون التجاري القطري.',
  'form.send': 'إرسال الطلب',
  'form.sending': 'جارٍ الإرسال…',
  'form.byEmail': 'اطلب استشارة لمشروعك',
  'form.byWhatsapp': 'أرسل عبر واتساب بدلًا من ذلك',
  'form.failed': 'تعذّر إرسال طلبك. يُرجى المحاولة مرة أخرى أو مراسلتنا عبر واتساب.',
  'form.reply': 'سنردّ عليك عبر البريد الإلكتروني أو الهاتف، عادةً خلال يوم عمل واحد.',
  'contact.openWhatsapp': '(فتح واتساب)',
  'form.emailSubject': 'طلب استشارة لمشروع',
  'form.waIntro': 'مرحبًا Shah Noori، أودّ طلب استشارة لمشروع.',
  'form.waName': 'الاسم',
  'form.waPhone': 'الهاتف',
  'form.waEmail': 'البريد الإلكتروني',
  'form.waType': 'نوع المشروع',
  'form.waDetails': 'التفاصيل',
  'type.civil': 'الإنشاءات المدنية',
  'type.interior': 'التشطيبات والتجهيزات الداخلية',
  'type.commercial': 'المساحات التجارية',
  'type.retail': 'تجهيز متاجر التجزئة',
  'type.hospitality': 'منشآت الضيافة',
  'type.mep': 'الأعمال الكهروميكانيكية',
  'type.turnkey': 'مقاولات تسليم مفتاح',

  'meta.home.title': 'Shah Noori | مقاول التجهيزات الداخلية والأعمال الكهروميكانيكية في الدوحة',
  'meta.home.description':
    'Shah Noori شركة مقاولات للتشطيبات والتجهيزات الداخلية والأعمال الكهروميكانيكية والمدنية في الدوحة، قطر. تعرّف على مشاريعنا المنجزة وخدماتنا واطلب استشارة.',
  'meta.about.title': 'من نحن | شركة تجهيزات داخلية في الدوحة',
  'meta.about.description':
    'Shah Noori شركة مقاولات وبناء متكاملة في الدوحة، قطر، بخبرة تزيد على 15 عامًا في التجهيزات الداخلية والأعمال الكهروميكانيكية والمدنية.',
  'meta.services.title': 'خدمات التجهيزات الداخلية والأعمال الكهروميكانيكية والمدنية في قطر',
  'meta.services.description':
    'خدمات التشطيبات والتجهيزات الداخلية، والأعمال الكهروميكانيكية (ميكانيكا، كهرباء، سباكة)، والإنشاءات المدنية في الدوحة، قطر، ينفذها فريق واحد من البداية إلى النهاية.',
  'meta.projects.title': 'المشاريع | أعمال التجهيزات الداخلية في قطر',
  'meta.projects.description':
    'مشاريع التجهيزات الداخلية والأعمال الكهروميكانيكية والمدنية التي أنجزتها Shah Noori في أنحاء قطر: مكاتب ومتاجر ومقاهٍ وفلل وغيرها.',
  'meta.contact.title': 'اتصل بنا | مقاول تجهيزات داخلية في الدوحة، قطر',
  'meta.contact.description':
    'اطلب استشارة لمشروعك من Shah Noori: تجهيزات داخلية وأعمال كهروميكانيكية ومدنية في الدوحة، قطر. اتصل بنا أو راسلنا عبر واتساب أو أرسل لنا رسالة.',
};

export const ui: Record<Locale, Record<UiKey, string>> = { en, ar };

/** A label in the given language (server components) */
export const tr = (locale: Locale, key: UiKey) => ui[locale][key];
