/**
 * The Worker's entry point (wrangler.jsonc "main"). It stands in front of the Next.js server that
 * OpenNext builds (.open-next/worker.js) and keeps a copy of every page it has built.
 *
 * Why: building a page takes far more processing time than the free Workers plan allows per
 * request, and Cloudflare was cutting off a few requests in every hundred ("Error 1102"). A page
 * only changes when someone publishes in the Studio, so there is no need to build it again for
 * every visitor.
 *
 * How pages are served:
 *  - a copy younger than FRESH_SECONDS is sent as it is
 *  - an older copy is still sent at once, and a new one is built in the background for the next
 *    visitor, so nobody waits and nobody sees an error if that build is cut off
 *  - with no copy yet, the page is built now and kept
 * So a Studio change shows on the site after about a minute, as it did before.
 *
 * Copies are kept per deployment: a new version of the site never serves pages from the old one
 * (they point to script files that no longer exist).
 */
// Generated by `opennextjs-cloudflare build`, so it does not exist until the site is built
import handler from './.open-next/worker.js';

// Durable Object classes the generated worker defines; wrangler needs them exported from the entry
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from './.open-next/worker.js';

/** A copy this young is served without building anything */
const FRESH_SECONDS = 60;
/** After this long a copy is thrown away rather than served */
const KEEP_SECONDS = 24 * 60 * 60;
/** How long a resized photo is kept, at Cloudflare and in the visitor's browser */
const IMAGE_SECONDS = 7 * 24 * 60 * 60;
const BUILT_AT = 'x-sn-built-at';

/** Pages only: not the Studio, the contact endpoint, Next's own files, or anything with a file extension */
const isPage = (url) =>
  !/^\/(api|studio|_next|assets|cdn-cgi)(\/|$)/.test(url.pathname) && !/\.[a-z0-9]{2,5}$/i.test(url.pathname);

/**
 * The name a copy is kept under. In-site navigation asks for the same address in a second form
 * (page data instead of HTML, marked by the RSC header; its _rsc query value already tells the
 * variants apart), so the two are kept separately.
 */
const keyFor = (request, url, version) => {
  const key = new URL(url);
  key.searchParams.set('__sn', `${version}${request.headers.has('rsc') ? '-data' : ''}`);
  return new Request(key.toString(), { method: 'GET' });
};

/** Builds the page and keeps a copy; returns what the visitor should get */
const build = async (request, env, ctx, cache, key) => {
  const response = await handler.fetch(request, env, ctx);
  // Only complete, ordinary pages are kept: no redirects, errors, or anything setting a cookie
  if (response.status !== 200 || response.headers.has('set-cookie') || !response.body) return response;
  const copy = new Response(response.clone().body, response);
  copy.headers.set('cache-control', `public, max-age=${KEEP_SECONDS}`);
  // The copy is already filed under its own name per variant (see keyFor)
  copy.headers.delete('vary');
  copy.headers.set(BUILT_AT, String(Date.now()));
  ctx.waitUntil(cache.put(key, copy).catch(() => {}));
  return response;
};

/** A kept copy as the visitor should receive it: browsers must always ask again, as before */
const serve = (cached, state) => {
  const response = new Response(cached.body, cached);
  response.headers.set('cache-control', 'private, no-cache, no-store, max-age=0, must-revalidate');
  response.headers.delete(BUILT_AT);
  response.headers.set('x-sn-cache', state);
  return response;
};

export default {
  async fetch(request, env, ctx) {
    let url;
    try {
      url = new URL(request.url);
      if (request.method !== 'GET') return handler.fetch(request, env, ctx);

      const cache = caches.default;

      // Resized photos (/_next/image) arrive from the image service without saying how long they
      // may be kept, so browsers fetched them again on every page. A photo at a given address
      // does not change (Studio photos get a new address when replaced), so it is kept for a
      // week, here and in the visitor's browser, like the files under /assets.
      if (url.pathname === '/_next/image') {
        const hit = await cache.match(request);
        if (hit) return hit;
        const answer = await handler.fetch(request, env, ctx);
        if (answer.status !== 200) return answer;
        const response = new Response(answer.body, answer);
        response.headers.set('cache-control', `public, max-age=${IMAGE_SECONDS}, stale-while-revalidate=${IMAGE_SECONDS}`);
        ctx.waitUntil(cache.put(request, response.clone()).catch(() => {}));
        return response;
      }

      if (!isPage(url)) return handler.fetch(request, env, ctx);

      const version = env.CF_VERSION_METADATA?.id ?? 'v';
      const key = keyFor(request, url, version);
      const cached = await cache.match(key);
      if (cached) {
        const age = (Date.now() - Number(cached.headers.get(BUILT_AT) ?? 0)) / 1000;
        if (age < FRESH_SECONDS) return serve(cached, 'fresh');
        // Older: send it now, build the next one behind the visitor's back
        ctx.waitUntil(build(request.clone(), env, ctx, cache, key).then((r) => r.body?.cancel?.()).catch(() => {}));
        return serve(cached, 'refreshing');
      }
      return await build(request, env, ctx, cache, key);
    } catch (error) {
      // Whatever goes wrong with the copies, the site itself must still answer
      console.error('Page cache failed, building the page directly', error);
      return handler.fetch(request, env, ctx);
    }
  },
};
