"use client";

import React, { useCallback, useEffect, useRef } from 'react';
import Image from 'next/image';
import { motion, useMotionValueEvent, useReducedMotion, useScroll, useTransform, type MotionValue } from 'framer-motion';

/** Frames generated by scripts/process-frames.sh (public/process-frames/frame-001.webp …). */
const FRAME_COUNT = 140;
const frameSrc = (i: number) => `/process-frames/frame-${String(i + 1).padStart(3, '0')}.webp`;

export interface ProcessStep {
  title: string;
  sub: string;
  text: string;
}

/**
 * Scroll progress at which each step hands over to the next. They match the dissolve midpoints
 * in the generated sequence (4s per step, 0.6s dissolves → 3.7s, 7.1s, 10.5s of 14.2s).
 */
const BOUNDARIES = [0, 0.261, 0.5, 0.739, 1];
const FADE = 0.05;

const StepText = ({ step, index, progress }: { step: ProcessStep; index: number; progress: MotionValue<number> }) => {
  const start = BOUNDARIES[index];
  const end = BOUNDARIES[index + 1];
  const first = index === 0;
  const last = index === BOUNDARIES.length - 2;
  // Fade in just after the previous boundary and out just before the next, so steps never overlap.
  // Stops must cover the full 0–1 range and increase: framer runs these on the browser's native
  // scroll timeline, which throws on out-of-range stops and snaps back if the range ends early.
  const input = first
    ? [0, end - FADE, end, 1]
    : last
      ? [0, start, start + FADE, 1]
      : [0, start, start + FADE, end - FADE, end, 1];
  const opacity = useTransform(progress, input, first ? [1, 1, 0, 0] : last ? [0, 0, 1, 1] : [0, 0, 1, 1, 0, 0]);
  const y = useTransform(progress, input, first ? [0, 0, -40, -40] : last ? [40, 40, 0, 0] : [40, 40, 0, 0, -40, -40]);

  return (
    <motion.div style={{ opacity, y }} className="absolute inset-0 flex flex-col justify-center">
      <span className="text-[88px] md:text-[140px] font-bold leading-none tracking-tighter text-white">
        {String(index + 1).padStart(2, '0')}
      </span>
      <h3 className="mt-6 text-2xl md:text-3xl font-medium uppercase tracking-[0.3em] text-gold">{step.title}</h3>
      <p className="mt-4 text-lg md:text-xl text-white">{step.sub}</p>
      <p className="mt-6 max-w-sm text-base leading-relaxed text-white/75">{step.text}</p>
    </motion.div>
  );
};

const RailItem = ({ index, progress }: { index: number; progress: MotionValue<number> }) => {
  const start = BOUNDARIES[index];
  const end = BOUNDARIES[index + 1];
  // Full 0–1 stops for the native scroll timeline (see StepText)
  const fill = useTransform(
    progress,
    index === 0 ? [0, end, 1] : index === BOUNDARIES.length - 2 ? [0, start, 1] : [0, start, end, 1],
    index === 0 ? ['0%', '100%', '100%'] : index === BOUNDARIES.length - 2 ? ['0%', '0%', '100%'] : ['0%', '0%', '100%', '100%']
  );
  // Number turns gold once its step is reached (the first step is active from the start)
  const color = useTransform(
    progress,
    index === 0 ? [0, 1] : [0, start - 0.01, start, 1],
    index === 0 ? ['#E4D4A3', '#E4D4A3'] : ['rgba(255,255,255,0.4)', 'rgba(255,255,255,0.4)', '#E4D4A3', '#E4D4A3']
  );
  return (
    <li className="flex items-center gap-3">
      <motion.span style={{ color }} className="w-6 text-sm font-medium tabular-nums">{String(index + 1).padStart(2, '0')}</motion.span>
      <span className="relative h-px w-16 overflow-hidden bg-white/20 md:w-24">
        <motion.span style={{ width: fill }} className="absolute inset-y-0 left-0 bg-gold" />
      </span>
    </li>
  );
};

/** Pinned section whose background "video" (a frame sequence on a canvas) is scrubbed by scroll. */
export const ProcessScroll = ({ steps }: { steps: ProcessStep[] }) => {
  const trackRef = useRef<HTMLDivElement>(null);
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const framesRef = useRef<HTMLImageElement[]>([]);
  const currentRef = useRef(0);
  const reduceMotion = useReducedMotion();

  const { scrollYProgress } = useScroll({ target: trackRef, offset: ['start start', 'end end'] });

  /** Draw a frame cover-fitted to the canvas; falls back to the nearest loaded frame. */
  const draw = useCallback((index: number) => {
    const canvas = canvasRef.current;
    const ctx = canvas?.getContext('2d');
    if (!canvas || !ctx) return;
    let img: HTMLImageElement | undefined;
    for (let d = 0; d < FRAME_COUNT && !img; d++) {
      const candidate = framesRef.current[index - d] ?? framesRef.current[index + d];
      if (candidate?.complete && candidate.naturalWidth) img = candidate;
    }
    if (!img) return;
    const { width: cw, height: ch } = canvas;
    const scale = Math.max(cw / img.naturalWidth, ch / img.naturalHeight);
    const w = img.naturalWidth * scale;
    const h = img.naturalHeight * scale;
    ctx.drawImage(img, (cw - w) / 2, (ch - h) / 2, w, h);
  }, []);

  // Size the canvas to its box at device pixel ratio
  useEffect(() => {
    if (reduceMotion) return;
    const canvas = canvasRef.current;
    if (!canvas) return;
    const resize = () => {
      const dpr = Math.min(window.devicePixelRatio || 1, 2);
      canvas.width = Math.round(canvas.clientWidth * dpr);
      canvas.height = Math.round(canvas.clientHeight * dpr);
      draw(currentRef.current);
    };
    resize();
    const observer = new ResizeObserver(resize);
    observer.observe(canvas);
    return () => observer.disconnect();
  }, [draw, reduceMotion]);

  // Preload frames: first frame immediately, the rest in order so scrubbing fills in progressively
  useEffect(() => {
    if (reduceMotion) return;
    let cancelled = false;
    framesRef.current = Array.from({ length: FRAME_COUNT }, (_, i) => {
      const img = new window.Image();
      img.decoding = 'async';
      img.onload = () => {
        if (!cancelled && Math.abs(i - currentRef.current) <= 1) draw(currentRef.current);
      };
      img.src = frameSrc(i);
      return img;
    });
    return () => {
      cancelled = true;
    };
  }, [draw, reduceMotion]);

  useMotionValueEvent(scrollYProgress, 'change', (p) => {
    const index = Math.min(FRAME_COUNT - 1, Math.max(0, Math.round(p * (FRAME_COUNT - 1))));
    if (index === currentRef.current) return;
    currentRef.current = index;
    requestAnimationFrame(() => draw(index));
  });

  // Reduced motion: no pinning or scrubbing, just the four steps as a simple list
  if (reduceMotion) {
    return (
      <ol className="grid gap-8 md:grid-cols-2">
        {steps.map((step, i) => (
          <li key={step.title} className="card-reveal overflow-hidden rounded-[24px] bg-[#111]">
            <div className="relative aspect-[16/10]">
              <Image src={`/images/process-${i + 1}.jpg`} alt="" fill sizes="(min-width: 768px) 50vw, 100vw" className="object-cover" />
            </div>
            <div className="p-8 text-white">
              <span className="text-6xl font-bold">{String(i + 1).padStart(2, '0')}</span>
              <h3 className="mt-4 text-xl uppercase tracking-[0.3em] text-gold">{step.title}</h3>
              <p className="mt-2">{step.sub}</p>
              <p className="mt-4 text-white/75">{step.text}</p>
            </div>
          </li>
        ))}
      </ol>
    );
  }

  return (
    <div ref={trackRef} className="relative" style={{ height: `${steps.length * 100}svh` }}>
      <div className="sticky top-0 h-[100svh] overflow-hidden bg-black">
        {/* First frame as a poster until the canvas paints (and for no-JS) */}
        <div className="absolute inset-0">
          <Image src={frameSrc(0)} alt="" fill sizes="100vw" className="object-cover" />
        </div>
        <canvas ref={canvasRef} className="absolute inset-0 h-full w-full" aria-hidden="true" />
        <div className="absolute inset-0 bg-gradient-to-r from-black/85 via-black/45 to-transparent" aria-hidden="true" />
        <div className="absolute inset-x-0 bottom-0 h-40 bg-gradient-to-t from-black/70 to-transparent" aria-hidden="true" />

        <div className="relative mx-auto h-full w-full max-w-[1320px] px-5 md:px-10 lg:px-[60px]">
          {/* Step copy: full text for screen readers, animated copies for sighted users */}
          <ol className="sr-only">
            {steps.map((s) => (
              <li key={s.title}>{s.title}: {s.sub}. {s.text}</li>
            ))}
          </ol>
          <div className="relative h-full max-w-xl" aria-hidden="true">
            {steps.map((step, i) => (
              <StepText key={step.title} step={step} index={i} progress={scrollYProgress} />
            ))}
          </div>

          <ol className="absolute bottom-10 left-5 flex flex-col gap-3 md:left-10 lg:left-[60px]" aria-hidden="true">
            {steps.map((step, i) => (
              <RailItem key={step.title} index={i} progress={scrollYProgress} />
            ))}
          </ol>
        </div>
      </div>
    </div>
  );
};
